import { t } from '../../../../../shared/i18n/index';
import { serialize } from './parse';
import { DEFAULT_BANNER } from './syntax';

export function generateDefaultMarkdown(): string {
	const today = new Date();
	const memoName = t('renderer.typeMemo');
	const todoName = t('renderer.typeTodo');
	const projectsName = t('default.projectsName');
	const libraryName = t('default.libraryName');
	const dateStr = `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, '0')}-${String(today.getDate()).padStart(2, '0')}`;

	return serialize({
		banner: { ...DEFAULT_BANNER, images: [...(DEFAULT_BANNER.images ?? [])], quote: t('default.bannerQuote'), author: 'NAND' },
		quickActions: [],
		columns: [
			{
				name: memoName,
				color: '#f59e0b',
				sectionType: 'memo',
				cards: [
					{
						id: 'demo-memo-1',
						title: t('default.memoTitle', { date: dateStr }),
						type: 'generic',
						column: memoName,
						body: t('default.memoBody'),
						tasks: [],
						docs: [],
						url: '',
						wikiLink: '',
						progress: -1,
						streak: 0,
						dueDate: '',
						blockquote: '',
						color: '',
						coverImage: '',
						width: 0,
						size: 'M',
						gridCols: 0,
						gridRows: 0,
						gridCol: 0,
						gridRow: 0,
					},
					{
						id: 'demo-memo-path',
						title: t('default.memoPathTitle'),
						type: 'generic',
						column: memoName,
						body: t('default.memoPathBody'),
						tasks: [],
						docs: [],
						url: '',
						wikiLink: '',
						progress: -1,
						streak: 0,
						dueDate: '',
						blockquote: '',
						color: '',
						coverImage: '',
						width: 0,
						size: 'M',
						gridCols: 0,
						gridRows: 0,
						gridCol: 0,
						gridRow: 0,
					},
					{
						id: 'demo-memo-rename',
						title: t('default.memoRenameTitle'),
						type: 'generic',
						column: memoName,
						body: t('default.memoRenameBody'),
						tasks: [],
						docs: [],
						url: '',
						wikiLink: '',
						progress: -1,
						streak: 0,
						dueDate: '',
						blockquote: '',
						color: '',
						coverImage: '',
						width: 0,
						size: 'M',
						gridCols: 0,
						gridRows: 0,
						gridCol: 0,
						gridRow: 0,
					},
				],
			},
			{
				name: todoName,
				color: '#6366f1',
				sectionType: 'todo',
				cards: [
					{
						id: 'demo-todo-1',
						title: t('default.todoTitle1'),
						type: 'task',
						column: todoName,
						body: '',
						tasks: [
							{ text: t('default.todo1'), checked: false },
							{ text: t('default.todo2'), checked: false },
							{ text: t('default.todo3'), checked: false },
							{ text: t('default.todo4'), checked: false },
						],
						docs: [],
						url: '',
						wikiLink: '',
						progress: -1,
						streak: 0,
						dueDate: '',
						blockquote: '',
						color: '',
						coverImage: '',
						width: 0,
						size: 'M',
						gridCols: 0,
						gridRows: 0,
						gridCol: 0,
						gridRow: 0,
					},
					{
						id: 'demo-todo-2',
						title: t('default.todoTitle2'),
						type: 'task',
						column: todoName,
						body: '',
						tasks: [
							{ text: t('default.guide1'), checked: false },
							{ text: t('default.guide2'), checked: false },
							{ text: t('default.guide3'), checked: false },
							{ text: t('default.guide4'), checked: false },
						],
						docs: [],
						url: '',
						wikiLink: '',
						progress: -1,
						streak: 0,
						dueDate: '',
						blockquote: '',
						color: '',
						coverImage: '',
						width: 0,
						size: 'M',
						gridCols: 0,
						gridRows: 0,
						gridCol: 0,
						gridRow: 0,
					},
				],
			},
			{
				name: projectsName,
				color: '#10b981',
				sectionType: 'projects',
				cards: [
					{
						id: 'demo-project-1',
						title: t('default.projectTitle'),
						type: 'project',
						column: projectsName,
						body: '',
						tasks: [],
						docs: [],
						url: '',
						wikiLink: '',
						progress: -1,
						streak: 0,
						dueDate: '',
						blockquote: '',
						color: '',
						coverImage: '',
						width: 0,
						size: 'M',
						gridCols: 0,
						gridRows: 0,
						gridCol: 0,
						gridRow: 0,
					},
				],
			},
			{
				name: libraryName,
				color: '#8b5cf6',
				sectionType: 'projects',
				cards: [
					{
						id: 'demo-lib-reading',
						title: t('default.reading'),
						type: 'project',
						column: libraryName,
						body: '',
						tasks: [],
						docs: [],
						url: '',
						wikiLink: '',
						progress: -1,
						streak: 0,
						dueDate: '',
						blockquote: '',
						color: '',
						coverImage: '',
						width: 0,
						size: 'M',
						gridCols: 0,
						gridRows: 0,
						gridCol: 0,
						gridRow: 0,
					},
					{
						id: 'demo-lib-toread',
						title: t('default.toRead'),
						type: 'project',
						column: libraryName,
						body: '',
						tasks: [],
						docs: [],
						url: '',
						wikiLink: '',
						progress: -1,
						streak: 0,
						dueDate: '',
						blockquote: '',
						color: '',
						coverImage: '',
						width: 0,
						size: 'M',
						gridCols: 0,
						gridRows: 0,
						gridCol: 0,
						gridRow: 0,
					},
					{
						id: 'demo-lib-done',
						title: t('default.done'),
						type: 'project',
						column: libraryName,
						body: '',
						tasks: [],
						docs: [],
						url: '',
						wikiLink: '',
						progress: -1,
						streak: 0,
						dueDate: '',
						blockquote: '',
						color: '',
						coverImage: '',
						width: 0,
						size: 'M',
						gridCols: 0,
						gridRows: 0,
						gridCol: 0,
						gridRow: 0,
					},
				],
			},
		],
	});
}
