import esbuild from "esbuild";
import process from "process";
import { readFileSync } from "node:fs";
import path from "path";
import { builtinModules } from 'node:module';

const iconicNotice = readFileSync(new URL("./src/core/icons/res/NOTICE.txt", import.meta.url), "utf8").replaceAll("*/", "* /");

const orcaNotice = readFileSync(new URL("./docs/third-party/orca-LICENSE.txt", import.meta.url), "utf8").replaceAll("*/", "* /");

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin

${iconicNotice}

${orcaNotice}
*/
`;

const prod = (process.argv[2] === "production");
const wsNodeEntry = path.resolve('node_modules/ws/wrapper.mjs');
const nodeBuiltins = [
	...builtinModules,
	...builtinModules.map((moduleName) => `node:${moduleName}`),
];

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/plugin/main.ts"],
	bundle: true,
	alias: { react: 'preact/compat', 'react-dom/client': 'preact/compat', 'react-dom': 'preact/compat' },
	jsx: 'automatic',
	jsxImportSource: 'preact',
	loader: {
		'.md': 'text',
		'.svg': 'text',
	},
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...nodeBuiltins,
	],
	plugins: [
		{
			name: 'ws-node-entry',
			setup(build) {
				build.onResolve({ filter: /^ws$/ }, () => ({ path: wsNodeEntry }));
			},
		},
	],
	format: "cjs",
	target: "es2021",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
