import {connect} from './cdp.mjs';import fs from 'node:fs/promises';import assert from 'node:assert/strict';const c=await connect(),out='/srv/nand/speculo/.speculo/specdev/changes/2026-09-28-issue-31-contacts-polish/evidence/implementation-t01';const rows=[];
try{
const count=await c.evaluate(`(async()=>{const v=window.__contacts,c=v.controller,template=await c.snapshot(window.__contactPaths.a);for(let i=0;i<101;i++){const name='Layout contact '+String(i).padStart(3,'0');if(c.choices('person').some(r=>r.fields.name===name))continue;const d=structuredClone(template);d.id=crypto.randomUUID();d.path='';d.raw='';d.fields.name=name;d.fields.region=i%2?'Beijing':'New York';d.fields.mobiles=['123456789'];await c.create(d);}v.state.selectedPath='';v.state.selectedId='';v.changeKind('person');app.workspace.leftSplit.collapse();app.workspace.rightSplit.collapse();return c.choices('person').length;})()`);assert.ok(count>100);
for(const width of [1280,800,500])for(const theme of ['light','dark']){
 await c.send('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:false});await c.evaluate(`(async()=>{document.body.classList.toggle('theme-dark','${theme}'==='dark');document.body.classList.toggle('theme-light','${theme}'==='light');window.__contacts.render();await new Promise(r=>setTimeout(r,150));})()`);
 const layout=await c.evaluate(`(()=>{const v=window.__contacts,el=v.contentEl,rect=e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height,right:r.right}};return {viewport:innerWidth,leaf:rect(el),scrollWidth:el.scrollWidth,clientWidth:el.clientWidth,cards:[...el.querySelectorAll('.nand-contacts-card')].map(rect),pagination:el.querySelector('.nand-contacts-pagination')?.textContent}})()`);assert.equal(layout.cards.length,60);assert.ok(layout.scrollWidth<=layout.clientWidth+1);const firstRow=layout.cards.filter(r=>Math.abs(r.y-layout.cards[0].y)<1);assert.ok(firstRow.every(r=>Math.abs(r.height-firstRow[0].height)<1));await fs.writeFile(`${out}/cards-${width}-${theme}.png`,Buffer.from((await c.send('Page.captureScreenshot',{format:'png'})).data,'base64'));
 await c.evaluate('window.__contacts.filters()');const filter=await c.evaluate(`(()=>{const m=document.querySelector('.modal'),title=m.querySelector('.modal-title'),r=m.getBoundingClientRect(),t=title.getBoundingClientRect();return {title:title.textContent,modalWidth:r.width,titleWidth:t.width,contained:t.x>=r.x&&t.right<=r.right,overflow:m.scrollWidth>m.clientWidth+1}})()`);assert.ok(filter.contained);assert.equal(filter.overflow,false);await fs.writeFile(`${out}/filter-${width}-${theme}.png`,Buffer.from((await c.send('Page.captureScreenshot',{format:'png'})).data,'base64'));for(const type of ['keyDown','keyUp'])await c.send('Input.dispatchKeyEvent',{type,key:'Escape',code:'Escape',windowsVirtualKeyCode:27});rows.push({width,theme,layout,filter});}
 await c.send('Emulation.clearDeviceMetricsOverride');await c.evaluate(`(async()=>{document.body.classList.remove('theme-dark');document.body.classList.add('theme-light');window.__contacts.select(window.__contactPaths.a);await app.workspace.saveLayout();})()`);await fs.writeFile(`${out}/contacts-layout.json`,JSON.stringify({passed:true,count,rows},null,2));console.log(JSON.stringify({passed:true,count,cases:rows.length}));
}finally{c.close();}
