// Actual Obsidian: lunar entry, shared annual reminder dates, cancellation and window lifetime.
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { setTimeout as delay } from 'node:timers/promises';
import { launchFreshVault } from './fresh-vault.mjs';
import { connect } from './cdp.mjs';

const entries=[
 {id:'leap',label:'Leap',startDate:'2020-05-24T12:34:56.123+08:00',calendar:'lunar',precision:'hours',annualReminder:true},
 {id:'short',label:'Short',startDate:'2023-03-21',calendar:'lunar',precision:'days',annualReminder:true},
 {id:'winter',label:'Winter',startDate:'2020-01-01',calendar:'lunar',precision:'ymd',annualReminder:true},
 {id:'solar',label:'Solar',startDate:'2020-02-29',precision:'days',annualReminder:true},
];
for(const entry of entries)entry.defaultLabel=false;
const members=entries.map(e=>({memberId:e.id,provider:'home',kind:'anniversary',instanceId:e.id}));
const board=`---\nlayout: side\nwidgets: ${JSON.stringify(members)}\ncustom: retain # author\n---\n## Notes\n`;
const runtime=await launchFreshVault({root:process.argv[2],port:9273,files:{'Board.md':board},settings:{version:1,namespaces:{app:{language:'en',introSeen:true,modules:{home:true,agent:false,automations:false,news:false,browser:false,archives:false,notifications:false,sync:false,comments:false,icons:false}},home:{dashboardFile:'Board',workspaceFiles:['Board'],workspaceNames:['Board'],anniversaryEnabled:true,anniversaries:entries,widgetLunarEnabled:false,widgetWeatherEnabled:false,widgetMusicEnabled:false,pomodoroEnabled:false}}}});
let c=runtime.connection;const rows=[];
const check=(name,passed,detail)=>{rows.push({name,passed,detail});assert.ok(passed,name);};
const until=async expression=>{const end=Date.now()+25000;while(Date.now()<end){if(await c.evaluate(expression))return;await delay(70);}throw Error(expression);};
const click=async expression=>{await c.send('Page.bringToFront');await c.evaluate(`window.focus();${expression}.scrollIntoView({block:'center',inline:'center'});true`);await delay(150);const hover=await c.evaluate(`(()=>{const r=${expression}.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2}})()`);await c.send('Input.dispatchMouseEvent',{type:'mouseMoved',...hover});await until(`(()=>{const e=${expression},r=e.getBoundingClientRect();return e.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2))})()`);const p=await c.evaluate(`(()=>{const r=${expression}.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2}})()`);await c.send('Input.dispatchMouseEvent',{type:'mousePressed',...p,button:'left',clickCount:1});await c.send('Input.dispatchMouseEvent',{type:'mouseReleased',...p,button:'left',clickCount:1});};
const key=async value=>{const windowsVirtualKeyCode={Enter:13,Escape:27,Tab:9,' ':32,ArrowDown:40,ArrowUp:38}[value];await c.send('Input.dispatchKeyEvent',{type:'keyDown',key:value,code:value===' '?'Space':value,windowsVirtualKeyCode,...(['Enter',' '].includes(value)?{text:value==='Enter'?'\r':' '}:{})});await c.send('Input.dispatchKeyEvent',{type:'keyUp',key:value,windowsVirtualKeyCode});await delay(100);};
const editor=`document.querySelector('.nand-anniversary-date-editor')`;
const save=`document.querySelector('.dashboard-modal-btn--confirm')`;
const field=index=>`${editor}.querySelectorAll('input[type="number"]')[${index}]`;
const member=id=>`document.querySelector('[data-widget-member="${id}"]:not(button)')`;
const mark=id=>`${member(id)}?.querySelector('.dashboard-sidebar-anniversary-date')?.textContent`;
const input=async(expression,value)=>{await c.evaluate(`(()=>{const e=${expression};e.value=${JSON.stringify(value)};e.dispatchEvent(new Event('input',{bubbles:true}));e.focus()})()`);await delay(120);};
const select=async value=>{await c.evaluate(`(()=>{const e=${editor}.querySelector('select');e.value=${JSON.stringify(value)};e.dispatchEvent(new Event('change',{bubbles:true}))})()`);await delay(150);};
const readEntry=id=>c.evaluate(`hs.plugin.settings.anniversaries.find(e=>e.id===${JSON.stringify(id)})`);
const raw=()=>fs.readFile(path.join(runtime.vault,'Board.md'),'utf8');
const home=async()=>{await c.evaluate(`app.plugins.plugins.nand.openWorkbench({feature:'dashboard',resourceId:'Board'})`);await until(`document.querySelectorAll('.dashboard-sidebar-anniversary').length===4`);await c.evaluate(`window.hs=app.workspace.getLeavesOfType('nand-workbench-view').flatMap(l=>l.view.getNativeSurfaces()).find(s=>s.getViewType()==='nand-dashboard-view');true`);const hidden=await c.evaluate(`!!document.querySelector('.dashboard-sidebar-slim-indicator')&&!document.querySelector('.dashboard-sidebar-slim-indicator').hidden&&document.querySelector('.dashboard-sidebar-slim-indicator').getBoundingClientRect().width>0`);if(hidden)await click(`document.querySelector('.dashboard-sidebar-slim-indicator')`);};
const open=async id=>{await click(`${member(id)}.querySelector('.dashboard-widget-cfg-btn')`);await until(`!!${editor}`);await until(`!${editor}.textContent.includes('Loading lunar')`);};
const cancel=async()=>{await click(`document.querySelector('.dashboard-modal-btn--cancel')`);await until(`!${editor}`);};
const sourceList=`app.plugins.plugins.nand.registry.contributions.get('automations:sources').get('home').list()`;
const freeze=async()=>{await c.evaluate(`window.RealDate=Date;window.Date=class extends RealDate{constructor(...args){super(...(args.length?args:[2025,2,1,10]))}static now(){return new RealDate(2025,2,1,10).getTime()}};true`);};
try{
 await freeze();await c.evaluate(`app.workspace.leftSplit.collapse();true`);await c.send('Emulation.setDeviceMetricsOverride',{width:1500,height:1000,deviceScaleFactor:1,mobile:false});await home();await until(`${mark('short')}==='2025-03-28'`);
 check('real-short-month-display',await c.evaluate(`${mark('short')}==='2025-03-28'`));check('real-missing-leap-month-display',await c.evaluate(`${mark('leap')}==='2025-04-29'`));check('solar-feb29-retains-march1',await c.evaluate(`${mark('solar')}==='2025-03-01'`));
 const reminders=await c.evaluate(sourceList);check('reminders-share-widget-dates',reminders.length===4&&await c.evaluate(`(${JSON.stringify(reminders)}).every(r=>{const d=new RealDate(r.schedule.at),pad=n=>String(n).padStart(2,'0');return document.querySelector('[data-widget-member="'+r.source.id.slice(7)+'"] .dashboard-sidebar-anniversary-date').textContent===d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())})`),reminders.map(r=>({id:r.id,schedule:r.schedule})));
 const before=JSON.stringify(await readEntry('leap'));await c.evaluate(`${member('leap')}.querySelector('.dashboard-widget-cfg-btn').focus()`);await key('Enter');await until(`!!${editor}`);check('keyboard-opens-visible-widget-editor',true);await cancel();await open('leap');check('lunar-editor-loads-real-leap-parts',await c.evaluate(`${field(0)}.value==='2020'&&${field(1)}.value==='4'&&${field(2)}.value==='2'&&${editor}.querySelector('[type="checkbox"]').checked`));await select('solar');check('calendar-switch-shows-original-solar-day',await c.evaluate(`${editor}.querySelector('[type="date"]').value==='2020-05-24'`));await select('lunar');await click(save);await until(`!${editor}`);await delay(500);check('roundtrip-preserves-exact-start-time-precision-and-reminder',JSON.stringify(await readEntry('leap'))===before);
 await open('leap');await input(field(0),'2021');check('nonexistent-leap-month-blocks-save',await c.evaluate(`${save}.disabled&&${editor}.textContent.includes('Enter an existing lunar date')`));await c.evaluate(`${editor}.querySelector('[type="checkbox"]').focus()`);await key(' ');check('keyboard-ordinary-month-recovers-valid-date',await c.evaluate(`!${save}.disabled&&${editor}.textContent.includes('2021-05-13')`));await input(field(2),'30');check('typed-missing-day-is-rejected-without-clamping',await c.evaluate(`${save}.disabled`));await input(field(1),'13');check('out-of-range-month-is-rejected',await c.evaluate(`${save}.disabled`));await cancel();check('invalid-draft-cancel-writes-nothing',JSON.stringify(await readEntry('leap'))===before);
 await open('solar');await input(`${editor}.querySelector('[type="date"]')`,'2024-03-01');await select('lunar');await until(`!${save}.disabled`);await c.evaluate(`${save}.focus()`);await key('Enter');await until(`!${editor}`);await delay(500);const edited=await readEntry('solar');check('solar-to-lunar-save-persists-true-solar-start',edited.startDate==='2024-03-01'&&edited.calendar==='lunar'&&edited.precision==='days');
 await open('short');const beforeMatrix=JSON.stringify(await readEntry('short'));for(const preset of ['system','claude-code','eye-care'])for(const dark of [false,true])for(const width of [500,800,1500]){
  await c.evaluate(`app.plugins.plugins.nand.theme.update(d=>{d.preset=${JSON.stringify(preset)}});app.changeTheme(${JSON.stringify(dark?'obsidian':'moonstone')});true`);await c.send('Emulation.setDeviceMetricsOverride',{width,height:1000,deviceScaleFactor:1,mobile:false});await delay(130);
  const bounds=await c.evaluate(`(()=>{const e=${editor};return{width:e.clientWidth,scroll:e.scrollWidth,controls:[...e.querySelectorAll('select,input:not([type="checkbox"])')].every(b=>b.getBoundingClientRect().height>=32),saveVisible:${save}.getBoundingClientRect().bottom<=innerHeight}})()`);check(`lunar-${preset}-${dark?'dark':'light'}-${width}`,bounds.width>0&&bounds.scroll<=bounds.width+1&&bounds.controls&&bounds.saveVisible,bounds);await runtime.shot(`lunar-${preset}-${dark?'dark':'light'}-${width}`);
 }await cancel();check('theme-resize-and-cancel-preserve-date',JSON.stringify(await readEntry('short'))===beforeMatrix);check('date-edits-never-rewrite-board',await raw()===board);
 await open('leap');await click(`[...document.querySelectorAll('.nand-anniversary-modal button')].find(e=>e.textContent==='Background')`);check('nested-background-editor-opens',await c.evaluate(`document.querySelectorAll('.modal-container').length===2`));await c.evaluate(`app.plugins.plugins.nand.openWorkbench({feature:'settings',section:'general'})`);await until(`!${editor}`);check('page-hide-closes-owned-and-nested-editors',await c.evaluate(`document.querySelectorAll('.modal-container').length===0`));await home();check('no-native-errors-before-restart',await c.evaluate('nandAcceptanceErrors.length')===0,await c.evaluate('nandAcceptanceErrors'));
 await c.evaluate(`window.Date=RealDate;true`);await runtime.restart();c=runtime.connection;await freeze();await c.send('Emulation.setDeviceMetricsOverride',{width:1500,height:1000,deviceScaleFactor:1,mobile:false});await home();check('restart-retains-input-calendar-and-original-time',JSON.stringify(await readEntry('leap'))===before&&(await readEntry('solar')).startDate==='2024-03-01');
 const main=c,beforePopout=new Set((await(await fetch(process.env.NAND_CDP_URL+'/json')).json()).map(t=>t.id));await c.send('Emulation.clearDeviceMetricsOverride');await c.evaluate(`app.workspace.moveLeafToPopout(hs.leaf,{width:1500,height:1000});true`);await until(`hs.contentEl.win!==window`);const pop=(await(await fetch(process.env.NAND_CDP_URL+'/json')).json()).find(t=>t.type==='page'&&!beforePopout.has(t.id));assert.ok(pop);c=await connect(pop.url,pop.id);await c.send('Emulation.setDeviceMetricsOverride',{width:1500,height:1000,deviceScaleFactor:1,mobile:false});await until(`!!document.querySelector('.dashboard-sidebar-anniversary')`);await open('leap');check('popout-editor-mounts-in-owner-window',!await main.evaluate(`!!document.querySelector('.nand-anniversary-date-editor')`));await input(field(0),'2021');await cancel();const shot=await c.send('Page.captureScreenshot',{format:'png'});await fs.writeFile(path.join(runtime.evidence,'lunar-popout.png'),Buffer.from(shot.data,'base64'));await open('short');await c.evaluate(`app.plugins.plugins.nand.setModuleEnabled('home',false)`);await until(`!${editor}&&!document.querySelector('.dashboard-sidebar-anniversary')`);check('module-disable-unmounts-widget-and-editor',true);c=main;
 check('no-native-errors',await c.evaluate('nandAcceptanceErrors.length')===0,await c.evaluate('nandAcceptanceErrors'));await fs.writeFile(path.join(runtime.evidence,'review.json'),JSON.stringify({rows,unverified:['Actual phone hardware']},null,2));
}catch(error){await fs.writeFile(path.join(runtime.evidence,'partial-review.json'),JSON.stringify(rows,null,2));await fs.writeFile(path.join(runtime.evidence,'diagnostic.json'),JSON.stringify(await c.evaluate(`({errors:window.nandAcceptanceErrors,body:document.body.innerText.slice(-14000),active:document.activeElement?.outerHTML?.slice(0,1000)})`).catch(e=>String(e)),null,2));await runtime.shot('failure').catch(()=>{});throw error;}finally{console.log(JSON.stringify({evidence:runtime.evidence,checks:rows.length,failed:rows.filter(r=>!r.passed)}));await runtime.stop();}
