// Actual Obsidian crop editing; production carousel callback advanced through a captured timer.
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { setTimeout as delay } from 'node:timers/promises';
import { launchFreshVault } from './fresh-vault.mjs';
import { connect } from './cdp.mjs';
const tall='<svg xmlns="http://www.w3.org/2000/svg" width="800" height="1200"><rect width="800" height="400" fill="#cc3344"/><rect y="400" width="800" height="400" fill="#22aa66"/><rect y="800" width="800" height="400" fill="#3366cc"/></svg>';
const wide='<svg xmlns="http://www.w3.org/2000/svg" width="2400" height="400"><rect width="800" height="400" fill="#eeaa22"/><rect x="800" width="800" height="400" fill="#6633bb"/><rect x="1600" width="800" height="400" fill="#229999"/></svg>';
const board='---\r\nbanner:\r\n  quote: Review\r\n  image: Images/A.svg\r\n  images: [Images/A.svg, Images/B.svg]\r\n  imagePos:\r\n    Images/A.svg: "140,-3" # normalize only on edit\r\n    Images/B.svg: "bad" # keep\r\n    Ghost.svg: {future: retain}\r\nwidgets: []\r\ncustom: keep # author\r\n---\r\n## Projects\r\n### Cover\r\nlink: [[Target]]\r\ncover: Images/B.svg\r\ncoverPos: nonsense\r\nAuthor paragraph. <!-- keep -->\r\n[[Target.md]]\r\n';
const runtime=await launchFreshVault({root:process.argv[2],port:9274,files:{'Board.md':board,'Images/A.svg':tall,'Images/B.svg':wide,'Target.md':'Target.\n'},settings:{version:1,namespaces:{app:{language:'en',introSeen:true,modules:{home:true,agent:false,automations:false,news:false,browser:false,archives:false,notifications:false,sync:false,comments:false,icons:false}},home:{dashboardFile:'Board',workspaceFiles:['Board'],workspaceNames:['Board'],widgetLunarEnabled:false,widgetWeatherEnabled:false,widgetMusicEnabled:false,pomodoroEnabled:false}}}});
let c=runtime.connection;const rows=[];
const check=(name,passed,detail)=>{rows.push({name,passed,detail});assert.ok(passed,name);};
const until=async expression=>{const end=Date.now()+25000;while(Date.now()<end){if(await c.evaluate(expression))return;await delay(70);}throw Error(expression);};
const click=async expression=>{await c.send('Page.bringToFront');await c.evaluate(`window.focus();${expression}.scrollIntoView({block:'center',inline:'center'});true`);await delay(150);const hover=await c.evaluate(`(()=>{const r=${expression}.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2}})()`);await c.send('Input.dispatchMouseEvent',{type:'mouseMoved',...hover});await until(`(()=>{const e=${expression},r=e.getBoundingClientRect();return e.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2))})()`);const p=await c.evaluate(`(()=>{const r=${expression}.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2}})()`);await c.send('Input.dispatchMouseEvent',{type:'mousePressed',...p,button:'left',clickCount:1});await c.send('Input.dispatchMouseEvent',{type:'mouseReleased',...p,button:'left',clickCount:1});};
const key=async(value,modifiers=0)=>{const windowsVirtualKeyCode={Enter:13,Escape:27,Tab:9,' ':32,ArrowDown:40,ArrowUp:38,ArrowLeft:37,ArrowRight:39}[value];await c.send('Input.dispatchKeyEvent',{type:'keyDown',key:value,code:value===' '?'Space':value,windowsVirtualKeyCode,modifiers,...(['Enter',' '].includes(value)?{text:value==='Enter'?'\r':' '}:{})});await c.send('Input.dispatchKeyEvent',{type:'keyUp',key:value,windowsVirtualKeyCode});await delay(100);};
const editor=i=>`document.querySelectorAll('.nand-focal-editor')[${i}]`;
const preview=i=>`${editor(i)}.querySelector('.nand-focal-preview')`;
const value=i=>c.evaluate(`[...${editor(i)}.querySelectorAll('input')].map(e=>Number(e.value))`);
const raw=()=>fs.readFile(path.join(runtime.vault,'Board.md'),'utf8');
const waitRaw=async predicate=>{const end=Date.now()+10000;while(Date.now()<end){if(predicate(await raw()))return;await delay(50);}throw Error('Board write did not settle');};
const input=async(i,axis,n)=>{await c.evaluate(`(()=>{const e=${editor(i)}.querySelectorAll('input')[${axis}];e.value=${JSON.stringify(String(n))};e.dispatchEvent(new Event('input',{bubbles:true}));e.focus()})()`);await delay(80);};
const home=async()=>{await c.evaluate(`app.plugins.plugins.nand.openWorkbench({feature:'dashboard',resourceId:'Board'})`);await until(`!!document.querySelector('.dashboard-project-cover')`);await c.evaluate(`window.hs=app.workspace.getLeavesOfType('nand-workbench-view').flatMap(l=>l.view.getNativeSurfaces()).find(s=>s.getViewType()==='nand-dashboard-view');true`);};
const openBanner=async()=>{await click(`document.querySelector('.dashboard-banner-edit-btn')`);await until(`document.querySelectorAll('.nand-focal-editor').length===2`);};
const openCard=async()=>{await click(`document.querySelector('.dashboard-card-btn--edit')`);await until(`document.querySelectorAll('.nand-focal-editor').length===1`);};
const cancel=async()=>{await click(`document.querySelector('.dashboard-modal-btn--cancel')`);await until(`!document.querySelector('.nand-focal-editor')`);};
const save=async()=>{await click(`document.querySelector('.dashboard-modal-footer .dashboard-modal-btn--confirm')`);await until(`!document.querySelector('.nand-focal-editor')`);await delay(500);};
const drag=async(i,x,y,abort=false)=>{await c.evaluate(`${preview(i)}.scrollIntoView({block:'center',inline:'center'});true`);await delay(100);const p=await c.evaluate(`(()=>{const r=${preview(i)}.getBoundingClientRect();return {x:r.x+r.width*${x}/100,y:r.y+r.height*${y}/100}})()`);await c.send('Input.dispatchMouseEvent',{type:'mouseMoved',...p});await c.send('Input.dispatchMouseEvent',{type:'mousePressed',...p,button:'left',buttons:1,clickCount:1});if(abort)await key('Escape');await c.send('Input.dispatchMouseEvent',{type:'mouseReleased',...p,button:'left',clickCount:1});await delay(100);};
const captureTimers=async()=>{await c.evaluate(`(()=>{const set=window.setInterval.bind(window),clear=window.clearInterval.bind(window);window.focalRotationTimers=new Map();window.setInterval=(fn,ms,...args)=>{const id=set(fn,ms,...args);if(ms===1800000)focalRotationTimers.set(id,fn);return id};window.clearInterval=id=>{focalRotationTimers.delete(id);return clear(id)}})()`);};
const verifyActual=async()=>c.evaluate(`(()=>{const b=document.querySelector('.dashboard-banner'),a=b.style.backgroundImage.includes('A.svg'),map=hs.data.banner.imagePos,raw=map?.[a?'Images/A.svg':'Images/B.svg'];return {image:b.style.backgroundImage,position:getComputedStyle(b).backgroundPosition,expected:raw?raw.split(',').join('% ')+'%':'50% 50%'}})()`);
try{
 await c.evaluate(`app.workspace.leftSplit.collapse();true`);await c.send('Emulation.setDeviceMetricsOverride',{width:1500,height:1000,deviceScaleFactor:1,mobile:false});await captureTimers();await home();await c.evaluate(`hs.render(hs.data);true`);await until(`focalRotationTimers.size>0`);check('read-only-malformed-points-retain-source-bytes',await raw()===board);
 await openBanner();check('malformed-preview-clamps-without-normalizing-source',JSON.stringify(await value(0))==='[100,0]'&&JSON.stringify(await value(1))==='[50,50]'&&await raw()===board);
 await input(0,0,20);await input(0,1,80);await c.evaluate(`${preview(1)}.focus()`);await key('ArrowRight');await key('ArrowUp',8);check('numeric-and-keyboard-adjust-independent-points',JSON.stringify(await value(0))==='[20,80]'&&JSON.stringify(await value(1))==='[51,40]');
 await drag(0,30,70);check('real-pointer-commits-percentages',JSON.stringify(await value(0))==='[30,70]',await value(0));await drag(0,80,10,true);check('escape-rolls-back-drag-without-closing-form',JSON.stringify(await value(0))==='[30,70]');await cancel();check('cancel-preserves-entire-author-document',await raw()===board);
 await openBanner();await input(0,0,20);await input(0,1,80);await input(1,0,80);await input(1,1,20);await save();await until(`hs.data.banner.imagePos?.['Images/A.svg']==='20,80'`);let text=await raw();check('save-persists-both-image-points-and-unknown-entry',text.includes('20,80')&&text.includes('80,20')&&text.includes('Ghost.svg')&&text.includes('future: retain')&&text.includes('coverPos: nonsense\r\nAuthor paragraph.'));
 for(let i=0;i<2;i++){const actual=await verifyActual();check(`carousel-actual-position-${i}`,actual.position===actual.expected,actual);await c.evaluate(`[...focalRotationTimers.values()].at(-1)();true`);await delay(750);}
 await openBanner();await click(`document.querySelectorAll('.dashboard-modal-mode-btn')[1]`);await until(`document.querySelectorAll('.nand-focal-editor').length===2`);check('statistics-mode-keeps-image-editor-and-drafts',JSON.stringify(await value(0))==='[20,80]'&&JSON.stringify(await value(1))==='[80,20]');await save();check('statistics-mode-retains-carousel-focal-map',await c.evaluate(`hs.data.banner.mode==='stats'&&hs.data.banner.images.length===2&&hs.data.banner.imagePos['Images/A.svg']==='20,80'`));
 await openCard();check('malformed-card-point-displays-center',JSON.stringify(await value(0))==='[50,50]');await c.evaluate(`${preview(0)}.focus()`);await key('ArrowRight',8);await input(0,1,30);await save();await until(`hs.data.columns[0].cards[0].coverPos==='60,30'`);text=await raw();check('cover-save-preserves-prose-links-crlf-and-idless-card',text.includes('coverPos: 60,30\r\nAuthor paragraph. <!-- keep -->\r\n[[Target.md]]')&&!text.includes('\nid: '));check('card-crop-matches-preview-percentages',await c.evaluate(`getComputedStyle(document.querySelector('.dashboard-project-cover')).backgroundPosition==='60% 30%'`));
 await openCard();await click(`${editor(0)}.querySelector('.nand-btn')`);check('reset-preview-centers-card',JSON.stringify(await value(0))==='[50,50]');await cancel();check('reset-cancel-keeps-stored-card-point',(await raw()).includes('coverPos: 60,30'));
 const beforeRename=await raw();await c.evaluate(`app.fileManager.renameFile(app.vault.getFileByPath('Images/A.svg'),'Images/A-Renamed.svg')`);await until(`hs.data.banner.images?.includes('Images/A-Renamed.svg')`);await until(`hs.data.banner.imagePos?.['Images/A-Renamed.svg']==='20,80'`);await waitRaw(text=>text.includes('Images/A-Renamed.svg')&&!text.includes('Images/A.svg'));check('file-rename-moves-image-and-its-point',(await raw()).includes('Images/A-Renamed.svg')&&!(await raw()).includes('Images/A.svg')&&beforeRename.includes('Images/A.svg'));
 await c.evaluate(`app.fileManager.renameFile(app.vault.getFolderByPath('Images'),'Pictures')`);await until(`hs.data.columns[0].cards[0].coverImage==='Pictures/B.svg'`);await until(`hs.data.banner.imagePos?.['Pictures/A-Renamed.svg']==='20,80'`);await waitRaw(text=>text.includes('Pictures/A-Renamed.svg')&&!text.includes('Images/'));check('folder-rename-moves-carousel-map-and-cover',await c.evaluate(`hs.data.banner.images.every(p=>p.startsWith('Pictures/'))&&hs.data.banner.imagePos['Pictures/B.svg']==='80,20'&&hs.data.columns[0].cards[0].coverPos==='60,30'`));check('image-files-are-not-edited',await fs.readFile(path.join(runtime.vault,'Pictures/A-Renamed.svg'),'utf8')===tall&&await fs.readFile(path.join(runtime.vault,'Pictures/B.svg'),'utf8')===wide);
 await openBanner();await click(`${editor(0)}.querySelector('.nand-btn')`);await save();check('reset-removes-only-selected-map-entry',await c.evaluate(`!('Pictures/A-Renamed.svg' in hs.data.banner.imagePos)&&hs.data.banner.imagePos['Pictures/B.svg']==='80,20'&&hs.data.banner.imagePos['Ghost.svg'].future==='retain'`));
 await openBanner();const beforeMatrix=await raw();for(const preset of ['system','claude-code','eye-care'])for(const dark of [false,true])for(const width of [500,800,1500]){
  await c.evaluate(`app.plugins.plugins.nand.theme.update(d=>{d.preset=${JSON.stringify(preset)}});app.changeTheme(${JSON.stringify(dark?'obsidian':'moonstone')});true`);await c.send('Emulation.setDeviceMetricsOverride',{width,height:1000,deviceScaleFactor:1,mobile:false});await delay(150);await c.evaluate(`${preview(0)}.scrollIntoView({block:'center'});true`);
  const bounds=await c.evaluate(`(()=>{const e=${editor(0)},save=document.querySelector('.dashboard-modal-footer .dashboard-modal-btn--confirm');return{width:e.clientWidth,scroll:e.scrollWidth,controls:[...e.querySelectorAll('input,button')].every(b=>b.getBoundingClientRect().height>=32),footer:save.getBoundingClientRect().bottom<=innerHeight,point:${preview(1)}.style.backgroundPosition}})()`);check(`focal-${preset}-${dark?'dark':'light'}-${width}`,bounds.width>0&&bounds.scroll<=bounds.width+1&&bounds.controls&&bounds.footer&&bounds.point==='80% 20%',bounds);await runtime.shot(`focal-${preset}-${dark?'dark':'light'}-${width}`);
 }await cancel();check('theme-and-size-changes-do-not-write-board',await raw()===beforeMatrix);await openCard();await c.evaluate(`app.plugins.plugins.nand.openWorkbench({feature:'settings',section:'general'})`);await until(`!document.querySelector('.nand-focal-editor')`);check('page-hide-disposes-card-editor',true);await home();check('no-errors-before-restart',await c.evaluate('nandAcceptanceErrors.length')===0,await c.evaluate('nandAcceptanceErrors'));
 await runtime.restart();c=runtime.connection;await c.send('Emulation.setDeviceMetricsOverride',{width:1500,height:1000,deviceScaleFactor:1,mobile:false});await home();check('restart-retains-renamed-independent-values',await c.evaluate(`hs.data.banner.imagePos['Pictures/B.svg']==='80,20'&&hs.data.columns[0].cards[0].coverPos==='60,30'`));check('restart-retains-author-document',await raw()===beforeMatrix);
 const main=c,beforePopout=new Set((await(await fetch(process.env.NAND_CDP_URL+'/json')).json()).map(t=>t.id));await c.send('Emulation.clearDeviceMetricsOverride');await c.evaluate(`app.workspace.moveLeafToPopout(hs.leaf,{width:1500,height:1000});true`);await until(`hs.contentEl.win!==window`);const pop=(await(await fetch(process.env.NAND_CDP_URL+'/json')).json()).find(t=>t.type==='page'&&!beforePopout.has(t.id));assert.ok(pop);c=await connect(pop.url,pop.id);await c.send('Emulation.setDeviceMetricsOverride',{width:1500,height:1000,deviceScaleFactor:1,mobile:false});await until(`!!document.querySelector('.dashboard-project-cover')`);await openCard();await drag(0,25,75);check('popout-pointer-uses-owner-window',JSON.stringify(await value(0))==='[25,75]'&&!await main.evaluate(`!!document.querySelector('.nand-focal-editor')`));const shot=await c.send('Page.captureScreenshot',{format:'png'});await fs.writeFile(path.join(runtime.evidence,'focal-popout.png'),Buffer.from(shot.data,'base64'));await c.evaluate(`app.plugins.plugins.nand.setModuleEnabled('home',false)`);await until(`!document.querySelector('.nand-focal-editor')`);check('module-disable-discards-uncommitted-editor',await raw()===beforeMatrix);c=main;
 check('no-native-errors',await c.evaluate('nandAcceptanceErrors.length')===0,await c.evaluate('nandAcceptanceErrors'));await fs.writeFile(path.join(runtime.evidence,'review.json'),JSON.stringify({rows,carouselClock:'Captured production 30-minute timer callback invoked; real fade timer elapsed.',unverified:['Actual phone hardware','Touch input']},null,2));
}catch(error){await fs.writeFile(path.join(runtime.evidence,'partial-review.json'),JSON.stringify(rows,null,2));await fs.writeFile(path.join(runtime.evidence,'diagnostic.json'),JSON.stringify(await c.evaluate(`({errors:window.nandAcceptanceErrors,body:document.body.innerText.slice(-14000),active:document.activeElement?.outerHTML?.slice(0,1000),buttons:[...document.querySelectorAll('.dashboard-modal-btn--confirm')].map(e=>{const r=e.getBoundingClientRect();return{html:e.outerHTML,rect:{x:r.x,y:r.y,width:r.width,height:r.height},hit:document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)?.outerHTML.slice(0,500)}})})`).catch(e=>String(e)),null,2));await runtime.shot('failure').catch(()=>{});throw error;}finally{console.log(JSON.stringify({evidence:runtime.evidence,checks:rows.length,failed:rows.filter(r=>!r.passed)}));await runtime.stop();}
