import { readFileSync } from 'node:fs';
import { builtinModules } from 'node:module';
import path from 'node:path';
import { canonicalTextResources, normalizeBuildText } from './build-text-resources.mjs';

const root = path.resolve(import.meta.dirname, '..');

function notice(relative) {
	return normalizeBuildText(readFileSync(path.join(root, relative), 'utf8')).replaceAll('*/', '* /');
}

const nodeBuiltins = [
	...builtinModules,
	...builtinModules.map((moduleName) => `node:${moduleName}`),
];

/** Shared esbuild options for the plugin bundle, used by the build and by bundle analysis. */
export function pluginBuildOptions({ production }) {
	// The bundled packages' section of THIRD-PARTY-NOTICES.md (the helper's crates ship with the helper).
	const thirdParty = notice('THIRD-PARTY-NOTICES.md');
	const bundled = thirdParty.slice(thirdParty.indexOf('## Bundled in main.js'), thirdParty.indexOf('## Linked into nand-pty'));
	const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
NAND source: https://github.com/NAMEWTA/nand

${notice('LICENSE')}

${notice('NOTICE')}

${notice('src/modules/icons/core/res/NOTICE.txt')}

Orca:
${notice('docs/third-party/orca-LICENSE.txt')}

${bundled}*/
`;
	return {
		absWorkingDir: root,
		banner: {
			js: banner,
		},
		entryPoints: ['src/app/main.ts'],
		bundle: true,
		alias: { react: 'preact/compat', 'react-dom/client': 'preact/compat', 'react-dom': 'preact/compat' },
		jsx: 'automatic',
		jsxImportSource: 'preact',
		loader: {
			'.md': 'text',
			'.svg': 'text',
		},
		external: [
			'obsidian',
			'electron',
			'@codemirror/autocomplete',
			'@codemirror/collab',
			'@codemirror/commands',
			'@codemirror/language',
			'@codemirror/lint',
			'@codemirror/search',
			'@codemirror/state',
			'@codemirror/view',
			'@lezer/common',
			'@lezer/highlight',
			'@lezer/lr',
			...nodeBuiltins,
		],
		plugins: [canonicalTextResources],
		format: 'cjs',
		target: 'es2021',
		logLevel: 'info',
		sourcemap: production ? false : 'inline',
		treeShaking: true,
		outfile: 'main.js',
		minify: production,
		// Obsidian loads UTF-8 scripts. Avoid expanding every localized character to an ASCII escape.
		charset: 'utf8',
	};
}
